#!/bin/bash
gem install --user-install cztop iruby
`gem environment |grep "USER INSTALLATION DIRECTORY" | cut -d: -f2`/bin/iruby register --force
gem build BOAST.gemspec
gem install --user-install BOAST-2.1.0.gem
